apiVersion: v1
kind: Pod
metadata:
  name: dnmonster-pod
spec:
  containers:
    - image: amouat/dnmonster:1.0
      name: dnmonster 
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP