apiVersion: v1
kind: Pod
metadata:
  name: monster-pod
spec:
  containers:
    - image: tecpi/monster_icon:0.1
      name: monster-icon
      ports:
        - containerPort: 9090
          name: http
          protocol: TCP
      env:
        - name: CONTEXT
          value: "DEV"